完成接口：`/doc/delete?title={}`根据文章名进行删除，返回字段由操作明operation、返回消息message、返回…
EricJeffrey/Lab418Site pull request #3
Opened 2020-08-02 06:40 UTC by buttercannfly

…码code组成，当删除成功时，code=200；删除失败时，code=500

2020-08-02 07:34 UTC, EricJeffrey requested changes
额命名一定要统一 😂 要么 `nameItThisWay` ，要么 `name_it_this_way`。
`code`的话，可以按照HTTP的，2xx表示ok，4xx表无法或拒绝处理请求，5xx表示错误。

2020-08-02 07:34 UTC, EricJeffrey commented on src/main/java/com/example/jeffrey/LabSite/Controller/DocController.java
> +import com.example.jeffrey.LabSite.Entity.Ope_result;
命名要么 驼峰 要么下划线，不要混用😂

2020-08-02 07:34 UTC, EricJeffrey commented on src/main/java/com/example/jeffrey/LabSite/Controller/DocController.java
> +    private Ope_result ope_result;
Java可能更倾向于opeResult之类的，同样命名

2020-08-02 07:34 UTC, EricJeffrey commented on src/main/java/com/example/jeffrey/LabSite/Controller/DocController.java
> +            ope_result.setCode(500);
500在HTTP中是 `内部服务器错误`，这里只是数据库没有查找到，并不是出现了`错误`，感觉程序抛出异常的时候500更加恰当。

2020-08-02 07:34 UTC, EricJeffrey commented on src/main/java/com/example/jeffrey/LabSite/Entity/Ope_result.java
> +        return "Ope_result{" +
这个`toString`什么时候会用到，这样的输出格式看起来蛮奇怪的，是debug用的吗？

2020-08-02 07:34 UTC, EricJeffrey commented on src/test/java/com/example/jeffrey/LabSite/LabSiteApplicationTests.java
> +		System.out.println(stringEncryptor.encrypt("123"));
这是干啥的？🤔 测试？

2020-08-02 07:35 UTC, EricJeffrey commented
code的话，是不是每个接口都应该有一个啊🤔，另外operation表示操作？有点多余感觉。message可以。

2020-08-02 13:34 UTC, EricJeffrey commented
话说，`code`和`message`这两个字段不刚好对应HTTP的状态码吗？那我们就没必要在设置这两个字段了，直接设置Response的响应码不就好了@buttercannfly

2020-08-02 14:01 UTC, buttercannfly commented
嗯好的 这part我会改掉，这确实是个不怎么聪明的设计了

2020-08-02 14:02 UTC, buttercannfly commented on src/main/java/com/example/jeffrey/LabSite/Entity/Ope_result.java
> +        return "Ope_result{" +
用不到 设计类的时候我就顺便写了tostring方法，其实可以去了

2020-08-02 14:03 UTC, buttercannfly commented on src/main/java/com/example/jeffrey/LabSite/Controller/DocController.java
> +import com.example.jeffrey.LabSite.Entity.Ope_result;
ok

2020-08-02 14:33 UTC, EricJeffrey commented on src/main/java/com/example/jeffrey/LabSite/Entity/Ope_result.java
> +        return "Ope_result{" +
嗯只要不是用来生成json就行。Java会自动调用对象的toString方法，像什么System.out.print(a)，所以可以稍微注意一下

2020-08-04 12:25 UTC, EricJeffrey requested changes
一些命名小错误了，另外下面那个test里面的东西？？

2020-08-04 12:25 UTC, EricJeffrey commented on src/main/java/com/example/jeffrey/LabSite/Entity/ope_result.java
> +public class ope_result {
话说类名这样写idea不报警告吗？
类名大写-大驼峰 😂

2020-08-04 12:25 UTC, EricJeffrey commented on src/test/java/com/example/jeffrey/LabSite/LabSiteApplicationTests.java
> +		System.out.println(stringEncryptor.encrypt("123"));
所以这个是自动添加的？

2020-08-04 12:25 UTC, EricJeffrey commented
命名这种东西确实很烦人emmm

2020-08-05 08:46 UTC, buttercannfly commented on src/test/java/com/example/jeffrey/LabSite/LabSiteApplicationTests.java
> +		System.out.println(stringEncryptor.encrypt("123"));
这个是用来加密数据库密码的，这里的数据库密码是123，运行test之后会返回一个加密后的密文，这样我们只需要在配置文件里写上密文即可，test文件夹上线时即丢弃，避免了硬编码暴露的风险

2020-08-05 08:46 UTC, buttercannfly commented on src/main/java/com/example/jeffrey/LabSite/Entity/ope_result.java
> +public class ope_result {
emm还真是，竟然小写了

2020-08-05 08:48 UTC, EricJeffrey commented on src/main/java/com/example/jeffrey/LabSite/Entity/ope_result.java
> +public class ope_result {
👌

2020-08-05 08:48 UTC, EricJeffrey commented on src/test/java/com/example/jeffrey/LabSite/LabSiteApplicationTests.java
> +		System.out.println(stringEncryptor.encrypt("123"));
👌

2020-08-08 12:55 UTC, EricJeffrey approved these changes

2020-08-08 12:58 UTC, merged